# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\BaiduNetdiskWorkspace\Project\src\my-mirror\UI\Wnd\main_wnd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 500)
        Dialog.setStyleSheet("background-color: rgb(93, 209, 220);\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ctnVideo = QtWidgets.QWidget(Dialog)
        self.ctnVideo.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"color: rgb(255, 255, 255);")
        self.ctnVideo.setObjectName("ctnVideo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ctnVideo)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.VideoShow = QtWidgets.QLabel(self.ctnVideo)
        self.VideoShow.setObjectName("VideoShow")
        self.verticalLayout_2.addWidget(self.VideoShow)
        self.verticalLayout.addWidget(self.ctnVideo)
        self.ctnVoice = QtWidgets.QWidget(Dialog)
        self.ctnVoice.setStyleSheet("background-color: rgb(254, 253, 247);")
        self.ctnVoice.setObjectName("ctnVoice")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.ctnVoice)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelFaceName = QtWidgets.QLabel(self.ctnVoice)
        self.labelFaceName.setObjectName("labelFaceName")
        self.horizontalLayout.addWidget(self.labelFaceName)
        self.txtFaceName = QtWidgets.QPlainTextEdit(self.ctnVoice)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtFaceName.sizePolicy().hasHeightForWidth())
        self.txtFaceName.setSizePolicy(sizePolicy)
        self.txtFaceName.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtFaceName.setObjectName("txtFaceName")
        self.horizontalLayout.addWidget(self.txtFaceName)
        self.btnStartCollect = QtWidgets.QPushButton(self.ctnVoice)
        self.btnStartCollect.setObjectName("btnStartCollect")
        self.horizontalLayout.addWidget(self.btnStartCollect)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 2)
        self.verticalLayout.addWidget(self.ctnVoice)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MagicMirror"))
        self.VideoShow.setText(_translate("Dialog", "没有摄像头"))
        self.labelFaceName.setText(_translate("Dialog", "姓名"))
        self.btnStartCollect.setText(_translate("Dialog", "开始采集"))
