# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\BaiduNetdiskWorkspace\Project\src\MyMirror\UI\Wnd\MainDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 1000)
        Dialog.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Video = QtWidgets.QWidget(Dialog)
        self.Video.setStyleSheet("background-color: rgb(0, 85, 127);")
        self.Video.setObjectName("Video")
        self.verticalLayout.addWidget(self.Video)
        self.Voice = QtWidgets.QWidget(Dialog)
        self.Voice.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.Voice.setObjectName("Voice")
        self.verticalLayout.addWidget(self.Voice)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MagicMirror"))
